package report

import (
	"bytes"
	"fmt"
	"html/template"
	"strings"

	"github.com/kextant/kextant-agent/pkg/types"
)

const htmlTemplate = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #0F172A 0%, #1E293B 100%);
      color: white;
      padding: 30px;
      border-radius: 8px;
      margin-bottom: 30px;
    }
    .header h1 {
      margin: 0 0 10px 0;
      font-size: 32px;
    }
    .header p {
      margin: 5px 0;
      opacity: 0.9;
    }
    .summary {
      background: #F8FAFC;
      padding: 25px;
      border-radius: 8px;
      margin-bottom: 30px;
      text-align: center;
    }
    .score {
      font-size: 56px;
      font-weight: bold;
      color: {{.ScoreColor}};
      margin: 10px 0;
    }
    .stats {
      font-size: 18px;
      color: #64748B;
    }
    .section {
      margin-bottom: 30px;
    }
    .section h2 {
      color: #0F172A;
      border-bottom: 2px solid #E2E8F0;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    .issue {
      border-left: 4px solid;
      padding: 15px;
      margin: 15px 0;
      background: #F9FAFB;
      border-radius: 4px;
    }
    .issue.critical {
      border-color: #DC2626;
      background: #FEF2F2;
    }
    .issue.warning {
      border-color: #F59E0B;
      background: #FFFBEB;
    }
    .issue.info {
      border-color: #3B82F6;
      background: #EFF6FF;
    }
    .issue h3 {
      margin: 0 0 10px 0;
      font-size: 18px;
    }
    .issue p {
      margin: 8px 0;
    }
    .issue strong {
      color: #0F172A;
    }
    .fix {
      background: #1E293B;
      color: #E2E8F0;
      padding: 12px;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
      font-size: 13px;
      overflow-x: auto;
      margin-top: 10px;
    }
    .affected {
      color: #64748B;
      font-size: 14px;
    }
    .footer {
      text-align: center;
      padding: 20px;
      color: #94A3B8;
      font-size: 14px;
      border-top: 1px solid #E2E8F0;
      margin-top: 40px;
    }
    .footer a {
      color: #3B82F6;
      text-decoration: none;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🧭 Kextant Health Report</h1>
    <p><strong>Cluster:</strong> {{.ClusterName}}</p>
    <p><strong>Generated:</strong> {{.Date}}</p>
  </div>

  <div class="summary">
    <div class="score">{{.Score}}/100</div>
    <div style="font-size: 24px; margin: 10px 0;">{{.Grade}} {{.GradeEmoji}}</div>
    <div class="stats">
      {{if .CriticalCount}}<span style="color: #DC2626;">🔴 {{.CriticalCount}} Critical</span> • {{end}}
      {{if .WarningCount}}<span style="color: #F59E0B;">🟡 {{.WarningCount}} Warnings</span> • {{end}}
      {{if .InfoCount}}<span style="color: #3B82F6;">ℹ️ {{.InfoCount}} Info</span>{{end}}
    </div>
  </div>

  {{if .CriticalIssues}}
  <div class="section">
    <h2>🔴 Critical Issues</h2>
    {{range .CriticalIssues}}
    <div class="issue critical">
      <h3>{{.Title}}</h3>
      <p>{{.Description}}</p>
      {{if .Affected}}
      <p class="affected"><strong>Affected:</strong> {{.AffectedList}}</p>
      {{end}}
      {{if .Risk}}
      <p><strong>Why it matters:</strong> {{.Risk}}</p>
      {{end}}
      {{if .Fix}}
      <p><strong>How to fix:</strong></p>
      <div class="fix">{{.Fix}}</div>
      {{end}}
    </div>
    {{end}}
  </div>
  {{end}}

  {{if .WarningIssues}}
  <div class="section">
    <h2>🟡 Warnings</h2>
    {{range .WarningIssues}}
    <div class="issue warning">
      <h3>{{.Title}}</h3>
      <p>{{.Description}}</p>
      {{if .Affected}}
      <p class="affected"><strong>Affected:</strong> {{.AffectedList}}</p>
      {{end}}
      {{if .Risk}}
      <p><strong>Why it matters:</strong> {{.Risk}}</p>
      {{end}}
      {{if .Fix}}
      <p><strong>How to fix:</strong></p>
      <div class="fix">{{.Fix}}</div>
      {{end}}
    </div>
    {{end}}
  </div>
  {{end}}

  {{if .InfoIssues}}
  <div class="section">
    <h2>ℹ️ Informational</h2>
    {{range .InfoIssues}}
    <div class="issue info">
      <h3>{{.Title}}</h3>
      <p>{{.Description}}</p>
      {{if .Affected}}
      <p class="affected"><strong>Affected:</strong> {{.AffectedList}}</p>
      {{end}}
      {{if .Risk}}
      <p><strong>Why it matters:</strong> {{.Risk}}</p>
      {{end}}
      {{if .Fix}}
      <p><strong>How to fix:</strong></p>
      <div class="fix">{{.Fix}}</div>
      {{end}}
    </div>
    {{end}}
  </div>
  {{end}}

  <div class="footer">
    <p>Generated by <a href="https://kextant.com">Kextant</a> • Free Kubernetes health reports</p>
  </div>
</body>
</html>`

type HTMLData struct {
	ClusterName    string
	Date           string
	Score          int
	Grade          string
	GradeEmoji     string
	ScoreColor     string
	CriticalCount  int
	WarningCount   int
	InfoCount      int
	CriticalIssues []HTMLIssue
	WarningIssues  []HTMLIssue
	InfoIssues     []HTMLIssue
}

type HTMLIssue struct {
	Title        string
	Description  string
	AffectedList string
	Risk         string
	Fix          string
	Affected     []types.AffectedResource
}

func GenerateHTML(report *types.Report) (string, error) {
	tmpl, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		return "", err
	}

	data := HTMLData{
		ClusterName:   report.ClusterName,
		Date:          report.GeneratedAt.Format("January 2, 2006 at 3:04 PM MST"),
		Score:         report.Score,
		Grade:         report.Grade,
		GradeEmoji:    GetGradeEmoji(report.Grade),
		ScoreColor:    getScoreColor(report.Score),
		CriticalCount: report.CriticalCount,
		WarningCount:  report.WarningCount,
		InfoCount:     report.InfoCount,
	}

	// Group findings by severity
	for _, f := range report.Findings {
		issue := HTMLIssue{
			Title:        fmt.Sprintf("%s [%s]", f.Title, f.ID),
			Description:  f.Description,
			AffectedList: formatAffectedList(f.Affected),
			Risk:         f.Risk,
			Fix:          f.Fix,
			Affected:     f.Affected,
		}

		switch f.Severity {
		case types.SeverityCritical:
			data.CriticalIssues = append(data.CriticalIssues, issue)
		case types.SeverityWarning:
			data.WarningIssues = append(data.WarningIssues, issue)
		case types.SeverityInfo:
			data.InfoIssues = append(data.InfoIssues, issue)
		}
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func formatAffectedList(resources []types.AffectedResource) string {
	if len(resources) == 0 {
		return ""
	}

	var parts []string
	for _, r := range resources {
		if r.Namespace != "" {
			parts = append(parts, fmt.Sprintf("%s/%s", r.Namespace, r.Name))
		} else {
			parts = append(parts, r.Name)
		}
	}

	// Limit to first 5 resources
	if len(parts) > 5 {
		parts = parts[:5]
		parts = append(parts, fmt.Sprintf("and %d more...", len(resources)-5))
	}

	return strings.Join(parts, ", ")
}

func getScoreColor(score int) string {
	switch {
	case score >= 90:
		return "#10B981"
	case score >= 75:
		return "#10B981"
	case score >= 60:
		return "#F59E0B"
	case score >= 40:
		return "#F59E0B"
	default:
		return "#DC2626"
	}
}
