package report

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/kextant/kextant-agent/pkg/types"
)

type SlackMessage struct {
	Blocks []SlackBlock `json:"blocks"`
}

type SlackBlock struct {
	Type     string                `json:"type"`
	Text     *SlackText            `json:"text,omitempty"`
	Fields   []SlackText           `json:"fields,omitempty"`
	Elements []SlackContextElement `json:"elements,omitempty"`
}

type SlackText struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

type SlackContextElement struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

func GenerateSlackBlocks(report *types.Report) ([]byte, error) {
	blocks := []SlackBlock{
		// Header
		{
			Type: "header",
			Text: &SlackText{
				Type: "plain_text",
				Text: "🧭 Kextant Health Report",
			},
		},
		// Cluster and date info
		{
			Type: "section",
			Fields: []SlackText{
				{
					Type: "mrkdwn",
					Text: fmt.Sprintf("*Cluster:*\n%s", report.ClusterName),
				},
				{
					Type: "mrkdwn",
					Text: fmt.Sprintf("*Date:*\n%s", report.GeneratedAt.Format("Jan 2, 2006")),
				},
			},
		},
		// Health score
		{
			Type: "section",
			Text: &SlackText{
				Type: "mrkdwn",
				Text: fmt.Sprintf("*Health Score: %d/100* %s\n\n%s",
					report.Score,
					GetGradeEmoji(report.Grade),
					formatStats(report)),
			},
		},
		// Divider
		{
			Type: "divider",
		},
	}

	// Add critical issues
	criticalFindings := GetFindingsBySeverity(report.Findings, types.SeverityCritical)
	if len(criticalFindings) > 0 {
		// Limit to top 5 critical issues for Slack
		limit := 5
		if len(criticalFindings) > limit {
			criticalFindings = criticalFindings[:limit]
		}

		for _, finding := range criticalFindings {
			blocks = append(blocks, SlackBlock{
				Type: "section",
				Text: &SlackText{
					Type: "mrkdwn",
					Text: formatSlackFinding("🔴", finding),
				},
			})
		}

		if len(GetFindingsBySeverity(report.Findings, types.SeverityCritical)) > limit {
			blocks = append(blocks, SlackBlock{
				Type: "section",
				Text: &SlackText{
					Type: "mrkdwn",
					Text: fmt.Sprintf("_...and %d more critical issues_", len(GetFindingsBySeverity(report.Findings, types.SeverityCritical))-limit),
				},
			})
		}
	}

	// Add warning issues (limit to 3)
	warningFindings := GetFindingsBySeverity(report.Findings, types.SeverityWarning)
	if len(warningFindings) > 0 {
		limit := 3
		if len(warningFindings) > limit {
			warningFindings = warningFindings[:limit]
		}

		if len(criticalFindings) > 0 {
			blocks = append(blocks, SlackBlock{Type: "divider"})
		}

		for _, finding := range warningFindings {
			blocks = append(blocks, SlackBlock{
				Type: "section",
				Text: &SlackText{
					Type: "mrkdwn",
					Text: formatSlackFinding("🟡", finding),
				},
			})
		}

		if len(GetFindingsBySeverity(report.Findings, types.SeverityWarning)) > limit {
			blocks = append(blocks, SlackBlock{
				Type: "section",
				Text: &SlackText{
					Type: "mrkdwn",
					Text: fmt.Sprintf("_...and %d more warnings_", len(GetFindingsBySeverity(report.Findings, types.SeverityWarning))-limit),
				},
			})
		}
	}

	// Footer
	blocks = append(blocks, SlackBlock{Type: "divider"})
	blocks = append(blocks, SlackBlock{
		Type: "context",
		Elements: []SlackContextElement{
			{
				Type: "mrkdwn",
				Text: "Generated by <https://kextant.com|Kextant> • Free Kubernetes health reports",
			},
		},
	})

	msg := SlackMessage{Blocks: blocks}
	return json.Marshal(msg)
}

func formatStats(report *types.Report) string {
	var parts []string

	if report.CriticalCount > 0 {
		parts = append(parts, fmt.Sprintf("🔴 %d Critical", report.CriticalCount))
	}
	if report.WarningCount > 0 {
		parts = append(parts, fmt.Sprintf("🟡 %d Warnings", report.WarningCount))
	}
	if report.InfoCount > 0 {
		parts = append(parts, fmt.Sprintf("ℹ️ %d Info", report.InfoCount))
	}

	if len(parts) == 0 {
		return "✅ No issues found"
	}

	return strings.Join(parts, "  •  ")
}

func formatSlackFinding(emoji string, finding types.Finding) string {
	var parts []string

	// Title
	parts = append(parts, fmt.Sprintf("*%s %s*", emoji, finding.Title))

	// Affected resources (limit to 3)
	if len(finding.Affected) > 0 {
		affectedList := []string{}
		for i, res := range finding.Affected {
			if i >= 3 {
				affectedList = append(affectedList, fmt.Sprintf("_+%d more_", len(finding.Affected)-3))
				break
			}
			if res.Namespace != "" {
				affectedList = append(affectedList, fmt.Sprintf("`%s/%s`", res.Namespace, res.Name))
			} else {
				affectedList = append(affectedList, fmt.Sprintf("`%s`", res.Name))
			}
		}
		parts = append(parts, strings.Join(affectedList, ", "))
	}

	// Risk
	if finding.Risk != "" {
		parts = append(parts, fmt.Sprintf("_%s_", finding.Risk))
	}

	return strings.Join(parts, "\n")
}
