{{- if and .Values.secrets.create (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kextant-agent.secretName" . }}
  labels:
    {{- include "kextant-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEXTANT_CLOUD_API_KEY: {{ .Values.secrets.cloudAPIKey | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookURL | quote }}
  SMTP_USERNAME: {{ .Values.secrets.smtpUsername | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
{{- end }}
